@startuml

title DriveHub - diagrama de class

abstract class Vehiculo {
    - matricula: string
    - marca: string
    - modelo: string
    - estado: IEstadoVehiculo
    ' - mantenimiento: Mantenimiento
    - tarifa: Tarifa

    + getters_y_setters()
    + setEstado(nuevoEstado: IEstadoVehiculo): void
    + alquilar(cliente: Cliente, fechaInicio: Date, fechaFin: Date): void
    + devolver(): void
    + iniciarMantenimiento(descripcion: string)): void
    + finalizarMantenimiento(): void
    + iniciarLimpieza():void

}

abstract class Tarifa{
    - tarifaBase: number
    - cargoPorKmRecorrido: number
    + getters_y_setters()
    + abstract calcularCosto(duracion: number, kilometro: Kilometraje): number
}

class TarifaSUV extends Tarifa {
    - cargoPorSeguro: number

    + getters_y_setters
}


class Cliente {
    - idCliente
    - nombre
    - reserva: Reserva
    + getters_y_setters()
}

class Kilometraje{
    -kmsRecorridosPorDia: Map<number,number>

    + getters_y_setters()
    + setKmsRecorridosPorDia()
    + getKmsRecorridosPorDia()
    + calcularKmsTotalesRecorridos(): number
}

class Mantenimiento{
    - costo: number
    - fechaInicio: Date
    - fechaFin: Date
    - descripcion: string
}

class Reserva{
    - fechaInicio: Date
    - fechaFin: Date
    - kilometraje: Kilometraje
    - vehiculo: Vehiculo
    - cliente: Cliente
    + getters_y_setters()
    + obtenerCostoTotal(): number
}

class DateUtils {
    + static obtenerDiasDuracion(fechaInicio: Date, fechaFin: Date): number
}

' Ver COMO IMPLEMENTAR
' porque tiene que haber una clase para CADA estado, que implemente
' y sobreescriba los metodos de la interfaz
interface IEstadoVehiculo {
    + alquilar(vehiculo: Vehiculo, cliente:Cliente, fechaInicio: date, fechaFin:Date): void
    + devolver(v: Vehiculo): void
    + iniciarMantenimiento(v: Vehiculo): void
    + finalizarMantenimiento(fechaFin: Date)
    + iniciarLimpieza(v:Vehiculo): void
}

abstract class Estado implements IEstadoVehiculo{
    + abstract lanzarErrorAccionInvalida():void
}

class EstadoDisponible extends Estado {
    + alquilar()
    + iniciarMantenimiento()
}

class EstadoEnAlquiler extends Estado {
    + devolver()
    + iniciarMantenimiento()
}

class EstadoEnMantenimiento extends Estado {
    + finalizarMantenimiento()
    + iniciarLimpieza()
}

class EstadoNecesitaLimpieza extends Estado {
    + iniciarMantenimiento()
    + finalizarMantenimiento()
    + iniciarLimpieza()
}



' Relaciones

Vehiculo <|-d- Compacto
Vehiculo <|-d- Sedan
Vehiculo <|-d- SUV

Tarifa <|-d- TarifaCompacto
Tarifa <|-d- TarifaSedan

Vehiculo -r- Tarifa
Vehiculo o-l- Mantenimiento
Vehiculo o-- IEstadoVehiculo

Reserva -- Vehiculo
Reserva *-r- Kilometraje

Cliente "1" -- "1" Reserva
' bidireccional


@enduml