@startuml DriveHub

title DriveHub - diagrama de class

abstract class Vehiculo {
    - matricula: string
    - marca: string
    - modelo: string
    - estado: IEstadoVehiculo
    ' - mantenimiento: Mantenimiento
    - tarifa: Tarifa

    + getters_y_setters()
    + setEstado(nuevoEstado: IEstadoVehiculo): void
    + alquilar(cliente: Cliente, fechaInicio: Date, fechaFin: Date): void
    + devolver(vehiculo: Vehiculo): void
    + iniciarMantenimiento(vehiculo: Vehiculo): void
    + finalizarMantenimiento(vehiculo: Vehiculo): void

}

abstract class Tarifa{
    - tarifaBase: number
    - cargoPorKmRecorrido: number
    + getters_y_setters()
    + abstract calcularCosto(duracion: number, kilometro: Kilometraje): number
}

class TarifaSUV extends Tarifa {
    - cargoPorSeguro: number

    + getters_y_setters
}


class Cliente {
    - idCliente: number
    - nombre: string
    - apellido: string
    - mail: string
    - telefono: number
    - reserva: Reserva | null
    + getters_y_setters()
    + setReserva(Reserva | null): void
    + desasociarReserva(): void
}

class Kilometraje{
    -kmsRecorridosPorDia: Map<number,number>

    + getters_y_setters()
    + setKmsRecorridosPorDia()
    + getKmsRecorridosPorDia()
    + calcularKmsTotalesRecorridos(): number
}

' modificar segun parte2
class Mantenimiento{
    - costo: number
    - fechaInicio: Date
    - fechaFin: Date
    - descripcion: string
}

class Reserva{
    - fechaInicio: Date
    - fechaFin: Date
    - kilometraje: Kilometraje
    - vehiculo: Vehiculo
    - cliente: Cliente
    + getters_y_setters()
    + obtenerCostoTotal(): number
}

class DateUtils {
    + static obtenerDiasDuracion(fechaInicio: Date, fechaFin: Date): number
}


interface IEstadoVehiculo {
    + alquilar(vehiculo: Vehiculo, cliente:Cliente, fechaInicio: date, fechaFin:Date): void
    + devolver(v: Vehiculo): void
    + iniciarMantenimiento(v: Vehiculo): void
    + finalizarMantenimiento(vehiculo: Vehiculo, costo: number, fechaFin: Date)
}

abstract class EstadoBase implements IEstadoVehiculo {
    # nombreEstado: string
    + lanzarErrorAccionInvalida(accion: string): void
    + alquilar(vehiculo: Vehiculo, cliente: Cliente, fechaInicio: Date, fechaFin: Date): void
    + devolver(vehiculo: Vehiculo): void
    + iniciarMantenimiento(v: Vehiculo): void
    + finalizarMantenimiento(vehiculo: Vehiculo, costo: number, fechaFin: Date): void
}

class EstadoDisponible extends EstadoBase  {
    + alquilar(vehiculo: Vehiculo, cliente: Cliente, fechaInicio: Date, fechaFin: Date): void
    + iniciarMantenimiento(vehiculo: Vehiculo);
}

class EstadoEnAlquiler extends EstadoBase  {
    - reservaActual: Reserva
    + devolver(vehiculo: Vehiculo): void
    + iniciarMantenimiento(vehiculo: Vehiculo): void
}

class EstadoEnMantenimiento extends EstadoBase  {
    + finalizarMantenimiento(vehiculo: Vehiculo, costo: number, fechaFin: Date):void
}


' Relaciones

Vehiculo <|-d- Compacto
Vehiculo <|-d- Sedan
Vehiculo <|-d- SUV

Tarifa <|-d- TarifaCompacto
Tarifa <|-d- TarifaSedan

Vehiculo -r- Tarifa
Vehiculo o-l- Mantenimiento
Vehiculo o--> IEstadoVehiculo

Reserva -- Vehiculo
Reserva *-r- Kilometraje

Cliente "1" -- "1" Reserva
EstadoBase ..> Vehiculo



@enduml